<?php
/* File: fields_products_page.inc
* Desc: Builds the arrays needed to display the products
* page of the catalog.
*/
$page = array( “title” => “The Food Shop Catalog”,
“top” => “The Food Shop Catalog”,
“bottom” => “Send questions and comments
to admin@xFoodShop.com”,
);
$table_heads = array(“catalog_number” => “Cat No”,
“name” => “Food”,
“description” => “Food Description”,
“price” => “Price”,
“pix” => “Picture”,
);
?>